version: "3.8"

services:
  mongo_rs1:
    image: mongo:6
    restart: always
    container_name: mongo_rs1
    depends_on:
      - mongo_rs2
    volumes:
      - ./data/mongo-1:/data/db
    expose:
        - 30001
    ports:
      - 30001:30001
    command: mongod --replSet rsmongo --bind_ip mongo_rs1 --port 30001
  mongo_rs2:
    image: mongo:6
    restart: always
    container_name: mongo_rs2
    depends_on:
      - mongo_rs3
    volumes:
      - ./data/mongo-2:/data/db
    expose:
        - 30002
    ports:
      - 30002:30002
    command: mongod --replSet rsmongo --bind_ip mongo_rs2 --port 30002
  mongo_rs3:
    image: mongo:6
    restart: always
    container_name: mongo_rs3
    volumes:
      - ./data/mongo-3:/data/db
    expose:
        - 30003
    ports:
      - 30003:30003
    command: mongod --replSet rsmongo --bind_ip mongo_rs3 --port 30003
  mongo_host:
    build: "./main-replica"
    container_name: mongo_host
    volumes:
      - ./data/host:/data/db
    depends_on:
      - mongo_rs1
    expose:
        - 30004
    ports:
      - 30004:30004
